name: ajLeaderboards
version: "@VERSION@"
main: us.ajg0702.leaderboards.LeaderboardPlugin
folia-supported: true
author: ajgeiss0702
depend: [PlaceholderAPI, LuckPerms]
softdepend: [SkinsRestorer]
description: Leaderboards for your server
api-version: 1.13
commands:
   ajleaderboards:
      aliases: [ajlb, ajl, alb]
      description: Commands for ajLeaderboards
      permission: ajleaderboards.use
permissions:
   ajleaderboards.use:
      description: Allows you to set up the plugin
      default: op
libraries:
   - com.zaxxer:HikariCP:5.1.0
   - com.h2database:h2:2.3.230
   - org.mongodb:mongodb-driver-sync:5.1.1
